# Site settings
author: Hank Liu
title: 
header-img: img/home-bg.png
email: hanke.liu@gmail.com
copyright_name: Hank Liu
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hankeliu2015

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
